#pragma once

// clang-format off
// generated by ./_deps/sqlpp23-src/scripts/sqlpp23-ddl2cpp --path-to-ddl ../sql/schema.sql --namespace lfw::sql --path-to-header-directory ../include/sql --naming-style identity

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace lfw::sql {
  struct hcf_ipv4_history_ {
    struct id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct ip_addr {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(ip_addr, ip_addr);
      using data_type = ::sqlpp::blob;
      using has_default = std::false_type;
    };
    struct ttl {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(ttl, ttl);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct hc {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(hc, hc);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(hcf_ipv4_history, hcf_ipv4_history);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               id,
               ip_addr,
               ttl,
               hc>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<hcf_ipv4_history_>, ip_addr>>;
  };
  using hcf_ipv4_history = ::sqlpp::table_t<hcf_ipv4_history_>;

} // namespace lfw::sql
